flowchart TD
  node101["Router"] -- "Wi-Fi - Good" --> node102{{"Mesh"}}
  node102 -- "Wi-Fi - Good" --> node103{{"Mesh"}} & node104{{"Mesh"}}
  node103 -- "Wi-Fi - 98" --> node105("Ross-iPhone")
  node103 -- "Wi-Fi - 184" --> node110("SonosZP")
  node103 -- "Wi-Fi - 64" --> node111("SonosZP-3")
  node103 -- "Wi-Fi - 86" --> node112("Unknown-48:e1:e9:4a:1a:5b")
  node103 -- "Wi-Fi - 92" --> node113("09AC01AC30200314")
  node103 -- "Wi-Fi - 76" --> node114("Carolines-MBP")
  node103 -- "Wi-Fi - 110" --> node115("SonosZP-2")
  node103 -- "Wi-Fi - 108" --> node116("iPhone-2")
  node103 -- "Wi-Fi - 96" --> node117("Unknown-44:3d:54:1e:d3:71")
  node103 -- "Wi-Fi - 84" --> node118("Samsung")